site_name: FAIR Maturity Matrix
site_description: FAIR Maturity Matrix documentation
site_url: https://chris-day.github.io/FAIR-Maturity-Matrix/
docs_dir: docs
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
plugins:
  - search
  - minify:
      minify_html: true
  - graph:
      name: "title"
  - macros:
      on_error_fail: true
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/dama-context.css
extra:
  consent:
    title: Cookie consent
    descriptiopn: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  generator: false
repo_url: https://github.com/chris-day/FAIR-Maturity-Matrix
repo_name: chris-day/FAIR-Maturity-Matrix
copyright: Copyright &copy; Pistoia Alliance Inc
nav:
  - Home: index.md
  - Introduction: introduction.md
  - FAIR Maturity Matrix: FAIRMaturityMatrix.md
  - Dimensions: 
      - Overview: FMMdimensions.md
      - Dimension 1: fmm-d1.md
      - Dimension 2: fmm-d2.md
      - Dimension 3: fmm-d3.md
      - Dimension 4: fmm-d4.md
      - Dimension 5: fmm-d5.md
      - Dimension 6: fmm-d6.md
      - Dimension 7: fmm-d7.md
  - Levels:
      - Overview: FMMlevels.md
      - Level 0: level0.md
      - Level 1: level1.md
      - Level 2: level2.md
      - Level 3: level3.md
      - Level 4: level4.md
      - Level 5: level5.md
  - FAIR Training: FAIR_training.md
  - Personas:
      - Overview: FAIRMM_personas.md
      - Autonomous AI Agent: FAIR_personas/Autonomous_AI_Agent.md
      - Business Analyst: FAIR_personas/Business_Analyst.md
      - Business Leader: FAIR_personas/Business_Leader.md
      - Business Owner: FAIR_personas/Business_Owner.md
      - Citizen Data Scientist: FAIR_personas/Citizen_Data_Scientist.md
      - Clinical Data Manager: FAIR_personas/Clinical_Data_Manager.md
      - Curator: FAIR_personas/Curator.md
      - Data Analyst: FAIR_personas/Data_Analyst.md
      - Data Engineer: FAIR_personas/Data_Engineer.md
      - Data Integration Specialist: FAIR_personas/Data_Integration_Specialist.md
      - Data Owner: FAIR_personas/Data_Owner.md
      - Data Protection Officer: FAIR_personas/Data_Protection_Officer.md
      - Data Quality Manager: FAIR_personas/Data_Quality_Manager.md
      - Data Scientist: FAIR_personas/Data_Scientist.md
      - Data Standards and Governance Expert: FAIR_personas/Data_Standards_and_Governance_Expert.md
      - Data Steward: FAIR_personas/Data_Steward.md
      - Data Strategy Owner: FAIR_personas/Data_Strategy_Owner.md
      - FAIR Community Manager: FAIR_personas/FAIR_Community_Manager.md
      - FAIR Data Architect: FAIR_personas/FAIR_Data_Architect.md
      - FAIR Trainer: FAIR_personas/FAIR_Trainer.md
      - Knowledge-Enabled Citizen: FAIR_personas/Knowledge-Enabled_Citizen.md
      - Lab Manager: FAIR_personas/Lab_Manager.md
      - Legal Data Expert: FAIR_personas/Legal_Data_Expert.md
      - Master Data Manager: FAIR_personas/Master_Data_Manager.md
      - Ontologist: FAIR_personas/Ontologist.md
      - Project Manager: FAIR_personas/Project_Manager.md
      - Reference Data Manager: FAIR_personas/Reference_Data_Manager.md
      - Researcher: FAIR_personas/Researcher.md
      - Subject Matter Expert: FAIR_personas/Subject_Matter_Expert.md
      - Technology Leader: FAIR_personas/Technology_Leader.md
      - X-template-FAIR persona: FAIR_personas/X-template-FAIR_persona.md
      - FAIR Personas Index: FAIR_personas/file_list.md
  - FAIR Business Value: FAIRMM_business_value.md
  - FAIR Roles:
      - Overview: FAIRMM_roles.md
      - Data Producer: FAIR_roles/Data_Producer.md
      - Data Enabler: FAIR_roles/Data_Enabler.md
      - Data Consumer: FAIR_roles/Data_Consumer.md
  - FAIR Data Principles:
      - Overview: FAIR_data_principles.md
      - Findable: FAIR_principles/fdp_f.md
      - F1. (Meta)data are assigned a globally unique and persistent identifier: FAIR_principles/fdp_f1.md
      - F2. Data are described with rich metadata (defined by R1 below): FAIR_principles/fdp_f2.md
      - F3. Metadata clearly and explicitly include the identifier of the data they describe: FAIR_principles/fdp_f3.md
      - F4. (Meta)data are registered or indexed in a searchable resource: FAIR_principles/fdp_f4.md
      - Accessible: FAIR_principles/fdp_a.md
      - A1. (Meta)data are retrievable by their identifier using a standardised communications protocol: FAIR_principles/fdp_a1.md
      - A1.1 The protocol is open, free, and universally implementable: FAIR_principles/fdp_a1_1.md
      - A1.2 The protocol allows for an authentication and authorisation procedure, where necessary: FAIR_principles/fdp_a1_2.md
      - A2. Metadata are accessible, even when the data are no longer available: FAIR_principles/fdp_a2.md
      - Interoperable: FAIR_principles/fdp_i.md
      - I1. (Meta)data use a formal, accessible, shared, and broadly applicable language for knowledge representation.: FAIR_principles/fdp_i1.md
      - I2. (Meta)data use vocabularies that follow FAIR principles: FAIR_principles/fdp_i2.md
      - I3. (Meta)data include qualified references to other (meta)data: FAIR_principles/fdp_i3.md
      - Reusable: FAIR_principles/fdp_r.md
      - R1. (Meta)data are richly described with a plurality of accurate and relevant attributes: FAIR_principles/fdp_r1.md
      - R1.1. (Meta)data are released with a clear and accessible data usage license: FAIR_principles/fdp_r1_1.md
      - R1.2. (Meta)data are associated with detailed provenance: FAIR_principles/fdp_r1_2.md
      - R1.3. (Meta)data meet domain-relevant community standards: FAIR_principles/fdp_r1_3.md
  - Resources Lexicon: resources_lexicon.md
  - Contributors: contributors.md
  - Summary: summary.md
  - Migration: migration.md
  - Terms Of Use: termsofuse.md
  - Various:
    - Info: info.md
    - Test: test.md
    - DAMA: data-governance.md 
    - Maths: Maths.md
    - Images: images/readme.md
    - Videos: videos/readme-videos.md
    - Data-Viz: Data-Viz/readme.md
    - Data-Viz extra: Data-Viz/readme-viz.md
    - Pistoia-Alliance-style: Pistoia-Alliance-style/2025-Pistoia-Fonts-Colors.md
